### PR TITLE
Fix namespace again

### LINKED ISSUE #4: namespace problem again (realword instead of realWorld)
newly generated code use the old namespace Realworld instead of RealWorld

dddd

### PR DESCRIPTION
**Pull request by BrainMaestro**
Fixes #4 

@supernova23 can you see if it uses the correct namespace now

### CODE REVIEW

**Comment by supernova23** [comment]
another problem

dddd

**Comment by supernova23** [comment]
I think regenerating the application using phoenix 1.3 will be the best solution

**Comment by BrainMaestro** [comment]
Yeah I just did that

**Comment by supernova23** [comment]
it works fine now

**Comment by BrainMaestro** [comment]
Great.

**Pull request merged**
